version: "3.9"
services:
  anagram-finder:
      build:
        context: .
        dockerfile: Dockerfile
      image: anagram-finder:latest
      container_name: anagram-finder
      env_file:
        - .env
      ports:
        - "${ANAGRAM_FINDER_API_PORT:-3000}:${ANAGRAM_FINDER_API_PORT:-3000}"
      restart: unless-stopped
      networks:
        - anagram-finder
      depends_on:
        - mongodb

  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "${ANAGRAM_FINDER_DB_PORT:-27017}:${ANAGRAM_FINDER_DB_PORT:-27017}"
      networks:
        - anagram-finder
      restart: unless-stopped

networks:
  anagram-finder: