version: "3.9"
services:
  anagram-finder:
      build:
        context: .
        dockerfile: Dockerfile
      image: localhost:5000/anagram-finder:latest
      container_name: anagram-finder
      volumes:
        - ./app/data:/data
      env_file:
        - .env
      ports:
        - "${ANAGRAM_FINDER_API_PORT:-3000}:${ANAGRAM_FINDER_API_PORT:-3000}"
      restart: unless-stopped
      networks:
        - anagram-finder

networks:
  anagram-finder:
    external: true