kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  ANAGRAM_FINDER_API_PORT: {{ .Values.configmap.data.ANAGRAM_FINDER_API_PORT }}
